<a href="https://colab.research.google.com/github/Destructor169/cs-203-stt-ai/blob/main/labs/week01-data-collection-lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Lab: Data Collection for Machine Learning

**CS 203: Software Tools and Techniques for AI**

---

## Lab Overview

In this lab, you will learn to collect data from the web using:

1. **HTTP fundamentals** - Understanding how the web works
2. **curl** - Command-line HTTP client
3. **Python requests** - Programmatic API calls
4. **BeautifulSoup** - Web scraping when APIs don't exist

**Goal**: Build a movie data collection pipeline for Netflix-style movie prediction.

---

## Setup

First, let's install and import the required libraries.

In [2]:
# Install required packages (uncomment if needed)
!pip install requests beautifulsoup4 pandas

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import json
import time

print("All imports successful!")

All imports successful!


---

# Part 1: HTTP Fundamentals

Before we start collecting data, we need to understand how the web works.

## 1.1 Understanding URLs

A URL (Uniform Resource Locator) has several components:

```
https://api.omdbapi.com:443/v1/movies?t=Inception&y=2010#details
└─┬──┘ └──────┬───────┘└┬─┘└───┬───┘└─────────┬────────┘└───┬───┘
  │           │         │      │              │             │
Protocol    Host      Port   Path          Query        Fragment
```

### Question 1.1 (Solved): Parse a URL

Use Python's `urllib.parse` to break down a URL into its components.

In [4]:
# SOLVED EXAMPLE
from urllib.parse import urlparse, parse_qs

url = "https://api.omdbapi.com/?apikey=demo&t=Inception&y=2010"

parsed = urlparse(url)

print(f"Scheme (protocol): {parsed.scheme}")
print(f"Host (domain): {parsed.netloc}")
print(f"Path: {parsed.path}")
print(f"Query string: {parsed.query}")

# Parse query parameters into a dictionary
params = parse_qs(parsed.query)
print(f"\nParsed parameters: {params}")

Scheme (protocol): https
Host (domain): api.omdbapi.com
Path: /
Query string: apikey=demo&t=Inception&y=2010

Parsed parameters: {'apikey': ['demo'], 't': ['Inception'], 'y': ['2010']}


### Question 1.2: Parse a Different URL

Parse the following GitHub API URL and extract:
1. The host
2. The path
3. All query parameters as a dictionary

URL: `https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc`

In [5]:
# YOUR CODE HERE
url = "https://api.github.com/search/repositories?q=machine+learning&sort=stars&order=desc"

# Parse the URL
parsed2 = urlparse(url)
# Print the host
print(f"Host (domain): {parsed2.netloc}")
# Print the path
print(f"Path: {parsed2.path}")
# Print the query parameters as a dictionary
params2 = parse_qs(parsed2.query)
print(f"\nParsed Parameters: {params}")

Host (domain): api.github.com
Path: /search/repositories

Parsed Parameters: {'apikey': ['demo'], 't': ['Inception'], 'y': ['2010']}


---

## 1.2 HTTP Status Codes

HTTP status codes tell you what happened with your request:

| Range | Category | Common Examples |
|-------|----------|----------------|
| 2xx | Success | 200 OK, 201 Created |
| 3xx | Redirect | 301 Moved, 302 Found |
| 4xx | Client Error | 400 Bad Request, 401 Unauthorized, 404 Not Found |
| 5xx | Server Error | 500 Internal Error, 503 Service Unavailable |

### Question 1.3: Match Status Codes

Match each scenario to the most likely HTTP status code:

1. You requested a movie that doesn't exist in the database
2. You made too many requests and hit the rate limit
3. Your API key is invalid
4. The request was successful and data was returned
5. The server crashed while processing your request

Status codes to choose from: `200`, `401`, `404`, `429`, `500`

In [6]:
# YOUR ANSWERS HERE
answers = {
    "movie_not_found": None,      # Replace None with the status code
    "rate_limited": None,
    "invalid_api_key": None,
    "success": None,
    "server_crashed": None
}

print(answers)

{'movie_not_found': None, 'rate_limited': None, 'invalid_api_key': None, 'success': None, 'server_crashed': None}


---

# Part 2: Making Requests with `curl`

`curl` is a command-line tool for making HTTP requests. It's essential for quick testing.

## 2.1 Basic curl Commands

You can run shell commands in Jupyter using `!` prefix.

### Question 2.1 (Solved): Your First API Call

Let's call a simple public API that requires no authentication.

In [7]:
# SOLVED EXAMPLE
# JSONPlaceholder is a free fake API for testing
!curl -s "https://jsonplaceholder.typicode.com/posts/1"

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}

### Question 2.2: Pretty Print with jq

The output above is hard to read. Use `jq` to format it nicely.

**Hint**: Pipe the curl output to jq: `curl ... | jq .`

In [8]:
# YOUR CODE HERE
# Fetch the same post but format the output with jq
!curl -s "https://jsonplaceholder.typicode.com/posts/1" | jq .

{
  "userId": 1,
  "id": 1,
  "title": "sunt aut facere repellat provident occaecati excepturi optio reprehenderit",
  "body": "quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto"
}


### Question 2.3: Extract Specific Fields with jq

Fetch all posts from `https://jsonplaceholder.typicode.com/posts` and extract only the `title` field from each post.

**Hint**: Use `jq '.[].title'` to get the title from each element in the array.

In [9]:
# YOUR CODE HERE
!curl -s "https://jsonplaceholder.typicode.com/posts" | jq '.[].title'

"sunt aut facere repellat provident occaecati excepturi optio reprehenderit"
"qui est esse"
"ea molestias quasi exercitationem repellat qui ipsa sit aut"
"eum et est occaecati"
"nesciunt quas odio"
"dolorem eum magni eos aperiam quia"
"magnam facilis autem"
"dolorem dolore est ipsam"
"nesciunt iure omnis dolorem tempora et accusantium"
"optio molestias id quia eum"
"et ea vero quia laudantium autem"
"in quibusdam tempore odit est dolorem"
"dolorum ut in voluptas mollitia et saepe quo animi"
"voluptatem eligendi optio"
"eveniet quod temporibus"
"sint suscipit perspiciatis velit dolorum rerum ipsa laboriosam odio"
"fugit voluptas sed molestias voluptatem provident"
"voluptate et itaque vero tempora molestiae"
"adipisci placeat illum aut reiciendis qui"
"doloribus ad provident suscipit at"
"asperiores ea ipsam voluptatibus modi minima quia sint"
"dolor sint quo a velit explicabo quia nam"
"maxime id vitae nihil numquam"
"autem hic labore sunt dolores incidunt"
"rem alias distinctio quo qu

### Question 2.4: View Response Headers

Use the `-I` flag to fetch only the response headers (no body) from:
`https://api.github.com`

What is the value of the `X-RateLimit-Limit` header?

In [10]:
# YOUR CODE HERE
!curl -s -I "https://api.github.com"

HTTP/2 200 
date: Sat, 10 Jan 2026 08:47:52 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept,Accept-Encoding, Accept, X-Requested-With
etag: W/"4f825cc84e1c733059d46e76e6df9db557ae5254f9625dfe8e1b09499c449438"
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
server: github.com
accept-ranges

**X-RateLimit-Limit: 60**

### Question 2.5: Add Custom Headers

Make a request to `https://httpbin.org/headers` with the following custom headers:
- `User-Agent: CS203-Lab/1.0`
- `Accept: application/json`

**Hint**: Use `-H "Header-Name: value"` for each header.

In [11]:
# YOUR CODE HERE
!curl -s "https://httpbin.org/headers"

{
  "headers": {
    "Accept": "*/*", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/7.81.0", 
    "X-Amzn-Trace-Id": "Root=1-69621239-0da53cb85bc07a861d13f551"
  }
}


In [12]:
# YOUR CODE HERE
!curl -s "https://httpbin.org/headers" -H "User-Agent": CS203-Lab/1.0 -H "Accept": application/json

{
  "headers": {
    "Host": "httpbin.org", 
    "X-Amzn-Trace-Id": "Root=1-69621239-11b4d2c121ad5ef32c10593c"
  }
}


---

# Part 3: Python `requests` Library

While `curl` is great for testing, we need Python for automation.

## 3.1 Basic GET Requests

### Question 3.1 (Solved): Simple GET Request

Make a GET request and inspect the response object.

In [13]:
# SOLVED EXAMPLE
import requests

response = requests.get("https://jsonplaceholder.typicode.com/posts/1")

print(f"Status Code: {response.status_code}")
print(f"Content-Type: {response.headers['Content-Type']}")
print(f"Response OK: {response.ok}")
print(f"\nJSON Data:")
print(response.json())

Status Code: 200
Content-Type: application/json; charset=utf-8
Response OK: True

JSON Data:
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}


### Question 3.2: Fetch Multiple Posts

Fetch posts from `https://jsonplaceholder.typicode.com/posts` and:
1. Print the total number of posts
2. Print the titles of the first 5 posts

In [14]:
# YOUR CODE HERE
response = requests.get("https://jsonplaceholder.typicode.com/posts")
posts = response.json()
print(posts)

print(f"Total number of posts: {len(posts)}")
print("Title of first 5 posts:")
for post in posts[:5]:
  print(post['title'])

[{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}, {'userId': 1, 'id': 2, 'title': 'qui est esse', 'body': 'est rerum tempore vitae\nsequi sint nihil reprehenderit dolor beatae ea dolores neque\nfugiat blanditiis voluptate porro vel nihil molestiae ut reiciendis\nqui aperiam non debitis possimus qui neque nisi nulla'}, {'userId': 1, 'id': 3, 'title': 'ea molestias quasi exercitationem repellat qui ipsa sit aut', 'body': 'et iusto sed quo iure\nvoluptatem occaecati omnis eligendi aut ad\nvoluptatem doloribus vel accusantium quis pariatur\nmolestiae porro eius odio et labore et velit aut'}, {'userId': 1, 'id': 4, 'title': 'eum et est occaecati', 'body': 'ullam et saepe reiciendis voluptatem adipisci\nsit amet autem assumenda provident rerum culpa\nquis hic c

In [15]:
# YOUR CODE HERE
response = requests.get("https://jsonplaceholder.typicode.com/posts")
posts = response.json()
# print(posts)

print(f"Total number of posts: {len(posts)}")
print("Title of first 5 posts:")
for post in posts[:5]:
  print(post['title'])

Total number of posts: 100
Title of first 5 posts:
sunt aut facere repellat provident occaecati excepturi optio reprehenderit
qui est esse
ea molestias quasi exercitationem repellat qui ipsa sit aut
eum et est occaecati
nesciunt quas odio


### Question 3.3 (Solved): Using Query Parameters

The proper way to add query parameters is using the `params` argument.

In [16]:
# SOLVED EXAMPLE
import requests

# Bad way (manual string building)
# url = "https://jsonplaceholder.typicode.com/posts?userId=1"

# Good way (using params)
response = requests.get(
    "https://jsonplaceholder.typicode.com/posts",
    params={"userId": 1}
)

posts = response.json()
print(f"User 1 has {len(posts)} posts")
print(f"\nActual URL used: {response.url}")

User 1 has 10 posts

Actual URL used: https://jsonplaceholder.typicode.com/posts?userId=1


### Question 3.4: Filter Posts by User

Fetch all posts by user 5 and user 7. Compare how many posts each user has.

**Hint**: Make two separate requests with different `userId` values.

In [17]:
response = requests.get(
    "https://jsonplaceholder.typicode.com/posts",
    params={"userId": 5}
)

posts = response.json()
print(posts)
print(f"User 5 has {len(posts)}")

[{'userId': 5, 'id': 41, 'title': 'non est facere', 'body': 'molestias id nostrum\nexcepturi molestiae dolore omnis repellendus quaerat saepe\nconsectetur iste quaerat tenetur asperiores accusamus ex ut\nnam quidem est ducimus sunt debitis saepe'}, {'userId': 5, 'id': 42, 'title': 'commodi ullam sint et excepturi error explicabo praesentium voluptas', 'body': 'odio fugit voluptatum ducimus earum autem est incidunt voluptatem\nodit reiciendis aliquam sunt sequi nulla dolorem\nnon facere repellendus voluptates quia\nratione harum vitae ut'}, {'userId': 5, 'id': 43, 'title': 'eligendi iste nostrum consequuntur adipisci praesentium sit beatae perferendis', 'body': 'similique fugit est\nillum et dolorum harum et voluptate eaque quidem\nexercitationem quos nam commodi possimus cum odio nihil nulla\ndolorum exercitationem magnam ex et a et distinctio debitis'}, {'userId': 5, 'id': 44, 'title': 'optio dolor molestias sit', 'body': 'temporibus est consectetur dolore\net libero debitis vel velit

In [18]:
response = requests.get(
    "https://jsonplaceholder.typicode.com/posts",
    params={"userId": 7}
)

posts = response.json()
print(posts)
print(f"User 7 has {len(posts)}")

[{'userId': 7, 'id': 61, 'title': 'voluptatem doloribus consectetur est ut ducimus', 'body': 'ab nemo optio odio\ndelectus tenetur corporis similique nobis repellendus rerum omnis facilis\nvero blanditiis debitis in nesciunt doloribus dicta dolores\nmagnam minus velit'}, {'userId': 7, 'id': 62, 'title': 'beatae enim quia vel', 'body': 'enim aspernatur illo distinctio quae praesentium\nbeatae alias amet delectus qui voluptate distinctio\nodit sint accusantium autem omnis\nquo molestiae omnis ea eveniet optio'}, {'userId': 7, 'id': 63, 'title': 'voluptas blanditiis repellendus animi ducimus error sapiente et suscipit', 'body': 'enim adipisci aspernatur nemo\nnumquam omnis facere dolorem dolor ex quis temporibus incidunt\nab delectus culpa quo reprehenderit blanditiis asperiores\naccusantium ut quam in voluptatibus voluptas ipsam dicta'}, {'userId': 7, 'id': 64, 'title': 'et fugit quas eum in in aperiam quod', 'body': 'id velit blanditiis\neum ea voluptatem\nmolestiae sint occaecati est e

In [19]:
response_user5 = requests.get(
    "https://jsonplaceholder.typicode.com/posts",
    params={"userId": 5}
)
posts_user5 = response_user5.json()

response_user7 = requests.get(
    "https://jsonplaceholder.typicode.com/posts",
    params={"userId": 7}
)
posts_user7 = response_user7.json()

print(f"User 5 has {len(posts_user5)} posts")
print(f"User 7 has {len(posts_user7)} posts")

User 5 has 10 posts
User 7 has 10 posts


---

## 3.2 Working with Real APIs

Let's work with some real-world APIs.

### Question 3.5 (Solved): GitHub API - Public Repositories

The GitHub API is free to use (with rate limits) and doesn't require authentication for public data.

In [20]:
# SOLVED EXAMPLE
import requests

# Fetch information about a popular repository
response = requests.get(
    "https://api.github.com/repos/pandas-dev/pandas",
    headers={"Accept": "application/vnd.github.v3+json"}
)

if response.ok:
    repo = response.json()
    print(f"Repository: {repo['full_name']}")
    print(f"Description: {repo['description']}")
    print(f"Stars: {repo['stargazers_count']:,}")
    print(f"Forks: {repo['forks_count']:,}")
    print(f"Language: {repo['language']}")
else:
    print(f"Error: {response.status_code}")

Repository: pandas-dev/pandas
Description: Flexible and powerful data analysis / manipulation library for Python, providing labeled data structures similar to R data.frame objects, statistical functions, and much more
Stars: 47,520
Forks: 19,492
Language: Python


### Question 3.6: Compare Popular ML Libraries

Fetch information about these ML-related repositories and create a comparison table:
- `scikit-learn/scikit-learn`
- `pytorch/pytorch`
- `tensorflow/tensorflow`

Show: name, stars, forks, and primary language.

**Hint**: Loop through the repos and collect data into a list of dictionaries, then create a DataFrame.

In [21]:
# YOUR CODE HERE
repos = [
    "scikit-learn/scikit-learn",
    "pytorch/pytorch",
    "tensorflow/tensorflow"
]

data = []
# Fetch data for each repo
for repo in repos:
  response = requests.get(
      f"https://api.github.com/repos/{repo}",
      headers={"Accept": "application/vnd.github.v3+json"}
  )

  data.append(response.json())
# print(data)

# Create a DataFrame
df = pd.DataFrame(data)
# print(df)

# Display the comparison
print(df[["full_name", "stargazers_count", "forks_count", "language"]])


                   full_name  stargazers_count  forks_count language
0  scikit-learn/scikit-learn             64573        26585   Python
1            pytorch/pytorch             96481        26473   Python
2      tensorflow/tensorflow            193273        75148      C++


### Question 3.7: Search GitHub Repositories

Use the GitHub search API to find the top 10 most starred repositories with "machine learning" in their description.

API endpoint: `https://api.github.com/search/repositories`

Parameters:
- `q`: search query (e.g., "machine learning")
- `sort`: "stars"
- `order`: "desc"
- `per_page`: 10

Print the name and star count of each repository.

In [22]:
response = requests.get(
    "https://api.github.com/search/repositories",
    params={
        "q": "machine learning",
        "sort": "stars",
        "order": "desc",
        "per_page": 10
    },
    headers={
        "Accept": "application/vnd.github.v3+json"
    }
)

if response.ok:
    search_results = response.json()
    print("Top 10 Most Starred 'Machine Learning' Repositories:")
    for i, repo in enumerate(search_results['items']):
        print(f"{i+1}. {repo['name']} - Stars: {repo['stargazers_count']:,}")
else:
    print(f"Error fetching repositories: {response.status_code}")
    print(response.json())

Top 10 Most Starred 'Machine Learning' Repositories:
1. tensorflow - Stars: 193,273
2. transformers - Stars: 154,834
3. ML-For-Beginners - Stars: 82,967
4. funNLP - Stars: 78,347
5. awesome-machine-learning - Stars: 71,266
6. scikit-learn - Stars: 64,573
7. gradio - Stars: 41,247
8. C-Plus-Plus - Stars: 33,658
9. netron - Stars: 32,157
10. 500-AI-Machine-learning-Deep-learning-Computer-vision-NLP-Projects-with-code - Stars: 30,752


---

## 3.3 Error Handling

Real-world APIs fail. We need to handle errors gracefully.

### Question 3.8 (Solved): Handling HTTP Errors

In [23]:
# SOLVED EXAMPLE
import requests

def fetch_with_error_handling(url):
    """Fetch URL with proper error handling."""
    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()  # Raises exception for 4xx/5xx
        return response.json()
    except requests.exceptions.Timeout:
        print(f"Timeout: Request took too long")
    except requests.exceptions.HTTPError as e:
        print(f"HTTP Error: {e.response.status_code}")
    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
    return None

# Test with valid URL
print("Valid URL:")
data = fetch_with_error_handling("https://jsonplaceholder.typicode.com/posts/1")
if data:
    print(f"  Got post: {data['title'][:50]}...")

# Test with invalid URL (404)
print("\nInvalid URL (404):")
fetch_with_error_handling("https://jsonplaceholder.typicode.com/posts/99999")

Valid URL:
  Got post: sunt aut facere repellat provident occaecati excep...

Invalid URL (404):
HTTP Error: 404


### Question 3.9: Robust Fetcher Function

Write a function `safe_fetch(url, max_retries=3)` that:

1. Attempts to fetch the URL
2. If it fails with a 5xx error, retries up to `max_retries` times
3. Waits 1 second between retries
4. Returns the JSON data if successful, None otherwise

Test it with `https://httpbin.org/status/500` (always returns 500) and `https://jsonplaceholder.typicode.com/posts/1` (always works).

In [29]:
# YOUR CODE HERE
import time

def safe_fetch(url, max_retries=3):
    """Fetch URL with retry logic for server errors."""
    # pass  # Implement this
    for attempt in range(max_retries):
      try:
        response = requests.get(url, timeout = 10)

        if(response.status_code == 200):
          return response.json()
        elif(500 <= response.status_code < 600):
          print(f"Retrying... Attempt: {attempt+1}")
          print(f"HTTP Error: {response.status_code}")
          time.sleep(1)
          continue
        else:
          print(f"HTTP Error: {response.status_code}")
          return None
      except requests.exceptions.Timeout:
        print(f"Timeout: Request took too long")
        return None


# Test your function
print("Testing with working URL:")
result = safe_fetch("https://jsonplaceholder.typicode.com/posts/1")
print(f"Result: {result}")

print("\nTesting with failing URL (500):")
result = safe_fetch("https://httpbin.org/status/500")
print(f"Result: {result}")

Testing with working URL:
Result: {'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

Testing with failing URL (500):
Retrying... Attempt: 1
HTTP Error: 500
Retrying... Attempt: 2
HTTP Error: 500
Retrying... Attempt: 3
HTTP Error: 500
Result: None


---

# Part 4: The OMDb Movie API

Now let's work with the OMDb API - our main data source for the Netflix project.

**Note**: You need an API key from https://www.omdbapi.com/apikey.aspx (free tier available).

For this lab, we'll use a demo key that has limited functionality.

In [31]:
# Set your API key here
# Get a free key from: https://www.omdbapi.com/apikey.aspx
OMDB_API_KEY = "202fbbc5"  # Replace with your actual key

# For demo purposes, you can try with key "demo" but it's very limited
# OMDB_API_KEY = "demo"

### Question 4.1 (Solved): Fetch a Single Movie

In [36]:
# SOLVED EXAMPLE
import requests

def fetch_movie(title, year=None, api_key=OMDB_API_KEY):
    """Fetch movie data from OMDb API."""
    params = {
        "apikey": api_key,
        "t": title,  # Search by title
        "type": "movie"
    }
    if year:
        params["y"] = year

    response = requests.get("https://www.omdbapi.com/", params=params)

    if response.ok:
        data = response.json()
        if data.get("Response") == "True":
            return data
        else:
            print(f"Movie not found: {data.get('Error')}")
    return None

# Fetch Inception
movie = fetch_movie("Inception", 2010)
if movie:
    print(f"Title: {movie['Title']}")
    print(f"Year: {movie['Year']}")
    print(f"Director: {movie['Director']}")
    print(f"IMDB Rating: {movie['imdbRating']}")
    print(f"Genre: {movie['Genre']}")

Title: Inception
Year: 2010
Director: Christopher Nolan
IMDB Rating: 8.8
Genre: Action, Adventure, Sci-Fi


### Question 4.2: Explore the Response

Fetch data for "The Dark Knight" and print ALL available fields in the response.

Which fields might be useful for predicting movie success?

In [40]:
# YOUR CODE HERE
movie = fetch_movie("The Dark Knight")
if movie:
  print("Available fields in the response:")
  for key in movie.keys():
    print(key, ": " ,movie[key])


Available fields in the response:
Title :  The Dark Knight
Year :  2008
Rated :  PG-13
Released :  18 Jul 2008
Runtime :  152 min
Genre :  Action, Crime, Drama
Director :  Christopher Nolan
Writer :  Jonathan Nolan, Christopher Nolan, David S. Goyer
Actors :  Christian Bale, Heath Ledger, Aaron Eckhart
Plot :  When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman, James Gordon and Harvey Dent must work together to put an end to the madness.
Language :  English, Mandarin
Country :  United States, United Kingdom
Awards :  Won 2 Oscars. 163 wins & 165 nominations total
Poster :  https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg
Ratings :  [{'Source': 'Internet Movie Database', 'Value': '9.1/10'}, {'Source': 'Rotten Tomatoes', 'Value': '94%'}, {'Source': 'Metacritic', 'Value': '85/100'}]
Metascore :  85
imdbRating :  9.1
imdbVotes :  3,115,102
imdbID :  tt0468569
Type :  movie
DVD :  N/A
BoxOffice :  $534,98

\[
\Large \textbf{The Dark Knight (2008)}
\]

\[
\begin{array}{|l|l|}
\hline
\textbf{Field} & \textbf{Details} \\
\hline
\text{Title} & \text{The Dark Knight} \\
\text{Year} & 2008 \\
\text{Rated} & \text{PG-13} \\
\text{Released} & \text{18 July 2008} \\
\text{Runtime} & \text{152 minutes} \\
\text{Genre} & \text{Action, Crime, Drama} \\
\text{Director} & \text{Christopher Nolan} \\
\text{Writers} & \text{Jonathan Nolan, Christopher Nolan, David S. Goyer} \\
\text{Actors} & \text{Christian Bale, Heath Ledger, Aaron Eckhart} \\
\text{Languages} & \text{English, Mandarin} \\
\text{Countries} & \text{United States, United Kingdom} \\
\text{Awards} & \text{Won 2 Oscars; 163 wins \& 165 nominations} \\
\hline
\end{array}
\]

\[
\Large \textbf{Ratings}
\]

\[
\begin{array}{|l|c|}
\hline
\textbf{Source} & \textbf{Score} \\
\hline
\text{IMDb} & 9.1 / 10 \\
\text{Rotten Tomatoes} & 94\% \\
\text{Metacritic} & 85 / 100 \\
\hline
\end{array}
\]

\[
\Large \textbf{Additional Information}
\]

\[
\begin{array}{|l|l|}
\hline
\text{Metascore} & 85 \\
\text{IMDb Rating} & 9.1 \\
\text{IMDb Votes} & 3{,}115{,}102 \\
\text{IMDb ID} & \text{tt0468569} \\
\text{Box Office} & \$534{,}987{,}076 \\
\hline
\end{array}
\]


### Question 4.3: Fetch Multiple Movies

Create a function `fetch_movies(titles)` that:
1. Takes a list of movie titles
2. Fetches data for each movie
3. Returns a list of movie dictionaries (only successful fetches)
4. Adds a 0.5 second delay between requests (to respect rate limits)

Test it with: `["Inception", "The Matrix", "Interstellar", "NonExistentMovie123"]`

In [44]:
def fetch_movies(titles):
    """Fetch multiple movies from OMDb API."""
    movies = []
    for title in titles:
      movie = fetch_movie(title)
      if movie:
        movies.append(movie)
        time.sleep(0.5)
    return movies

# Test
test_titles = ["Inception", "The Matrix", "Interstellar", "NonExistentMovie123"]
movies = fetch_movies(test_titles)
print(f"Successfully fetched {len(movies)} out of {len(test_titles)} movies")

# Display movies as a table
if movies:
    df_movies = pd.DataFrame(movies)
    print("\nFetched Movies Table:")
    display(df_movies[['Title', 'Year', 'Director', 'imdbRating', 'Genre']])
else:
    print("No movies fetched to display.")

Movie not found: Movie not found!
Successfully fetched 3 out of 4 movies

Fetched Movies Table:


Title  Year                         Director imdbRating  \
0     Inception  2010                Christopher Nolan        8.8   
1    The Matrix  1999  Lana Wachowski, Lilly Wachowski        8.7   
2  Interstellar  2014                Christopher Nolan        8.7   

                       Genre  
0  Action, Adventure, Sci-Fi  
1             Action, Sci-Fi  
2   Adventure, Drama, Sci-Fi

### Question 4.4: Create a Movie DataFrame

Using the movies you fetched, create a pandas DataFrame with these columns:
- title
- year (as integer)
- genre
- director
- imdb_rating (as float)
- imdb_votes (as integer, remove commas)
- runtime_minutes (as integer, extract from "148 min")
- box_office (keep as string for now)

**Hint**: You'll need to clean the data types.

In [46]:
# YOUR CODE HERE
df = pd.DataFrame(movies)
display(df[['Title', 'Year', 'Genre', 'Director', 'imdbRating', 'imdbVotes', 'Runtime', 'BoxOffice']])

Title  Year                      Genre  \
0     Inception  2010  Action, Adventure, Sci-Fi   
1    The Matrix  1999             Action, Sci-Fi   
2  Interstellar  2014   Adventure, Drama, Sci-Fi   

                          Director imdbRating  imdbVotes  Runtime  \
0                Christopher Nolan        8.8  2,767,518  148 min   
1  Lana Wachowski, Lilly Wachowski        8.7  2,217,731  136 min   
2                Christopher Nolan        8.7  2,454,660  169 min   

      BoxOffice  
0  $292,587,330  
1  $177,559,005  
2  $203,227,580

### Question 4.5: Search Movies by Title

OMDb also has a search endpoint that returns multiple results.

Use the `s` parameter instead of `t` to search for movies containing "Star Wars".

API endpoint: `https://www.omdbapi.com/?apikey=YOUR_KEY&s=Star Wars&type=movie`

Print the title and year of each result.

In [52]:
# YOUR CODE HERE
def fetch_movie_by_title(title, api_key=OMDB_API_KEY):
    """Fetch movie data from OMDb API."""
    params = {
        "apikey": api_key,
        "s": title,  # Search by title
        "type": "movie"
    }

    response = requests.get("https://www.omdbapi.com/", params=params)

    if response.ok:
        data = response.json()
        if data.get("Response") == "True":
            return data["Search"]
        else:
            print(f"Movie not found: {data.get('Error')}")
    return None

movies = fetch_movie_by_title("Star Wars")
if movies:
    for movie in movies:
        print(f"{movie['Title']} ({movie['Year']})")

Star Wars: Episode IV - A New Hope (1977)
Star Wars: Episode V - The Empire Strikes Back (1980)
Star Wars: Episode VI - Return of the Jedi (1983)
Star Wars: Episode VII - The Force Awakens (2015)
Star Wars: Episode I - The Phantom Menace (1999)
Star Wars: Episode III - Revenge of the Sith (2005)
Star Wars: Episode II - Attack of the Clones (2002)
Rogue One: A Star Wars Story (2016)
Star Wars: Episode VIII - The Last Jedi (2017)
Star Wars: Episode IX - The Rise of Skywalker (2019)


### Question 4.6: Handle Pagination

The OMDb search API returns 10 results per page and includes a `totalResults` field.

Write a function `search_all_movies(query)` that:
1. Searches for movies matching the query
2. Fetches ALL pages of results (use the `page` parameter)
3. Returns a list of all movies found

**Hint**: `totalResults` tells you how many movies exist. Divide by 10 to get the number of pages.

Test with a query that has many results like "Batman".

In [53]:
# YOUR CODE HERE
def search_all_movies(query, api_key=OMDB_API_KEY):
    """Search OMDb and return ALL matching movies across all pages."""
    all_movies = []
    page = 1
    total_results = 0
    max_pages = 1 # Initialize to 1, will be updated after first request

    while page <= max_pages:
        params = {
            "apikey": api_key,
            "s": query,
            "type": "movie",
            "page": page
        }

        try:
            response = requests.get("https://www.omdbapi.com/", params=params, timeout=10)
            response.raise_for_status()
            data = response.json()

            if data.get("Response") == "True":
                all_movies.extend(data["Search"])
                if page == 1:
                    total_results = int(data["totalResults"])
                    max_pages = (total_results + 9) // 10

                print(f"Fetched page {page}/{max_pages} for '{query}'. Total movies collected: {len(all_movies)}")
                page += 1
                time.sleep(0.5)
            else:
                print(f"No more results or error for '{query}': {data.get('Error')}")
                break
        except requests.exceptions.RequestException as e:
            print(f"Error fetching page {page} for '{query}': {e}")
            break

    return all_movies

print("Searching for 'Batman' movies...")
all_batman = search_all_movies("Batman")
print(f"Found {len(all_batman)} Batman movies")

if all_batman:
    df_batman = pd.DataFrame(all_batman)
    display(df_batman.head())
else:
    print("No movies found for 'Batman'.")

Searching for 'Batman' movies...
Fetched page 1/52 for 'Batman'. Total movies collected: 10
Fetched page 2/52 for 'Batman'. Total movies collected: 20
Fetched page 3/52 for 'Batman'. Total movies collected: 30
Fetched page 4/52 for 'Batman'. Total movies collected: 40
Fetched page 5/52 for 'Batman'. Total movies collected: 50
Fetched page 6/52 for 'Batman'. Total movies collected: 60
Fetched page 7/52 for 'Batman'. Total movies collected: 70
Fetched page 8/52 for 'Batman'. Total movies collected: 80
Fetched page 9/52 for 'Batman'. Total movies collected: 90
Fetched page 10/52 for 'Batman'. Total movies collected: 100
Fetched page 11/52 for 'Batman'. Total movies collected: 110
Fetched page 12/52 for 'Batman'. Total movies collected: 120
Fetched page 13/52 for 'Batman'. Total movies collected: 130
Fetched page 14/52 for 'Batman'. Total movies collected: 140
Fetched page 15/52 for 'Batman'. Total movies collected: 150
Fetched page 16/52 for 'Batman'. Total movies collected: 160
Fetched p

Title  Year     imdbID   Type  \
0                       Batman Begins  2005  tt0372784  movie   
1                          The Batman  2022  tt1877830  movie   
2  Batman v Superman: Dawn of Justice  2016  tt2975590  movie   
3  Batman v Superman: Dawn of Justice  2016  tt2975590  movie   
4                              Batman  1989  tt0096895  movie   

                                              Poster  
0  https://m.media-amazon.com/images/M/MV5BMzA2ND...  
1  https://m.media-amazon.com/images/M/MV5BMmU5NG...  
2  https://m.media-amazon.com/images/M/MV5BZTJkYj...  
3  https://m.media-amazon.com/images/M/MV5BZTJkYj...  
4  https://m.media-amazon.com/images/M/MV5BYzZmZW...

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('Title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('Year').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('imdbID').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('Poster').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Title')):
  _plot_series(series, series_name, i)
  fig.legend(title='Title', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Year')):
  _plot_series(series, series_name, i)
  fig.legend(title='Year', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('imdbID')):
  _plot_series(series, series_name, i)
  fig.legend(title='imdbID', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Poster')):
  _plot_series(series, series_name, i)
  fig.legend(title='Poster', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_9['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Year'].value_counts()
    for x_label, grp in _df_10.groupby('Title')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Title')
_ = plt.ylabel('Year')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['imdbID'].value_counts()
    for x_label, grp in _df_11.groupby('Year')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Year')
_ = plt.ylabel('imdbID')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Poster'].value_counts()
    for x_label, grp in _df_12.groupby('imdbID')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('imdbID')
_ = plt.ylabel('Poster')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_13['Title'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_13, x='index', y='Title', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_14['Year'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_14, x='index', y='Year', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_15['imdbID'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_15, x='index', y='imdbID', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_16['Poster'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_16, x='index', y='Poster', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [54]:
display(df_batman)

Title  Year     imdbID  \
0                                        Batman Begins  2005  tt0372784   
1                                           The Batman  2022  tt1877830   
2                   Batman v Superman: Dawn of Justice  2016  tt2975590   
3                   Batman v Superman: Dawn of Justice  2016  tt2975590   
4                                               Batman  1989  tt0096895   
..                                                 ...   ...        ...   
509                           Batman- Out of Character  2011  tt2154366   
510  Batman Returns: Rob Burman on Mold Making and ...  2012  tt2186524   
511                     Goldentusk's Batman Theme Song  2007  tt1813157   
512                                 Batman of Suburbia  2010  tt1842319   
513                     Tomorrow Knight: Batman Reborn  2010  tt1871421   

      Type                                             Poster  
0    movie  https://m.media-amazon.com/images/M/MV5BMzA2ND...  
1    movie  https://m.media-amazon.com/images/M/MV5BMmU5NG...  
2    movie  https://m.media-amazon.com/images/M/MV5BZTJkYj...  
3    movie  https://m.media-amazon.com/images/M/MV5BZTJkYj...  
4    movie  https://m.media-amazon.com/images/M/MV5BYzZmZW...  
..     ...                                                ...  
509  movie                                                N/A  
510  movie  https://m.media-amazon.com/images/M/MV5BMDFkOT...  
511  movie  https://m.media-amazon.com/images/M/MV5BZDQ1MD...  
512  movie                                                N/A  
513  movie                                                N/A  

[514 rows x 5 columns]

---

# Part 5: Web Scraping with BeautifulSoup

When APIs don't exist or don't have what we need, we scrape.

## 5.1 HTML Basics

### Question 5.1 (Solved): Parse HTML

In [ ]:
# SOLVED EXAMPLE
from bs4 import BeautifulSoup

html = """
<html>
<body>
    <div class="movie" id="movie-1">
        <h2 class="title">Inception</h2>
        <span class="year">2010</span>
        <span class="rating">8.8</span>
        <a href="/movies/inception">More Info</a>
    </div>
    <div class="movie" id="movie-2">
        <h2 class="title">The Matrix</h2>
        <span class="year">1999</span>
        <span class="rating">8.7</span>
        <a href="/movies/matrix">More Info</a>
    </div>
</body>
</html>
"""

soup = BeautifulSoup(html, 'html.parser')

# Find all movie divs
movies = soup.find_all('div', class_='movie')
print(f"Found {len(movies)} movies\n")

# Extract data from each
for movie in movies:
    title = movie.find('h2', class_='title').text
    year = movie.find('span', class_='year').text
    rating = movie.find('span', class_='rating').text
    link = movie.find('a')['href']

    print(f"{title} ({year}) - Rating: {rating} - Link: {link}")

### Question 5.2: CSS Selectors

Rewrite the above extraction using CSS selectors (`.select()` and `.select_one()`) instead of `.find()` and `.find_all()`.

**Hint**:
- `.movie` selects elements with class "movie"
- `.movie .title` selects elements with class "title" inside class "movie"

In [ ]:
# YOUR CODE HERE
# Use the same 'soup' from above

# Extract using CSS selectors


### Question 5.3: Scrape a Real Website

Let's scrape the example website `http://quotes.toscrape.com/` which is designed for scraping practice.

Extract all quotes from the first page, including:
- The quote text
- The author name
- The tags

Return the results as a list of dictionaries.

In [ ]:
# YOUR CODE HERE
import requests
from bs4 import BeautifulSoup

# Fetch the page
url = "http://quotes.toscrape.com/"

# Parse the HTML

# Extract quotes

# Print results


### Question 5.4: Handle Pagination in Scraping

The quotes website has multiple pages. Scrape the first 3 pages and collect all quotes.

Pages follow the pattern:
- Page 1: `http://quotes.toscrape.com/page/1/`
- Page 2: `http://quotes.toscrape.com/page/2/`
- etc.

**Remember**: Add a delay between requests to be polite!

In [ ]:
# YOUR CODE HERE


### Question 5.5: Extract Table Data

Scrape the table from `https://www.w3schools.com/html/html_tables.asp`.

The table contains company data. Extract all rows and create a pandas DataFrame.

**Hint**: Look for `<table>`, `<tr>` (table row), `<th>` (header), and `<td>` (data cell) elements.

In [ ]:
# YOUR CODE HERE
# Hint: pandas has a read_html() function that can do this automatically!
# But try doing it manually first to understand the process.


---

# Part 6: Building the Movie Data Pipeline

Now let's put everything together to build a complete data collection pipeline for our Netflix project.

## 6.1 The Complete Pipeline

### Question 6.1 (Solved): Movie Data Collector Class

In [ ]:
# SOLVED EXAMPLE
import requests
import pandas as pd
import time
from typing import List, Dict, Optional

class MovieDataCollector:
    """Collect movie data from OMDb API."""

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "http://www.omdbapi.com/"
        self.delay = 0.5  # Seconds between requests

    def fetch_movie(self, title: str, year: Optional[int] = None) -> Optional[Dict]:
        """Fetch a single movie by title."""
        params = {
            "apikey": self.api_key,
            "t": title,
            "type": "movie"
        }
        if year:
            params["y"] = year

        try:
            response = requests.get(self.base_url, params=params, timeout=10)
            response.raise_for_status()
            data = response.json()

            if data.get("Response") == "True":
                return data
        except Exception as e:
            print(f"Error fetching {title}: {e}")

        return None

    def fetch_movies(self, titles: List[str]) -> List[Dict]:
        """Fetch multiple movies."""
        movies = []

        for i, title in enumerate(titles):
            print(f"Fetching {i+1}/{len(titles)}: {title}")
            movie = self.fetch_movie(title)

            if movie:
                movies.append(movie)

            time.sleep(self.delay)

        return movies

    def to_dataframe(self, movies: List[Dict]) -> pd.DataFrame:
        """Convert movie data to cleaned DataFrame."""
        if not movies:
            return pd.DataFrame()

        # Extract relevant fields
        rows = []
        for m in movies:
            rows.append({
                "title": m.get("Title"),
                "year": m.get("Year"),
                "genre": m.get("Genre"),
                "director": m.get("Director"),
                "actors": m.get("Actors"),
                "imdb_rating": m.get("imdbRating"),
                "imdb_votes": m.get("imdbVotes"),
                "runtime": m.get("Runtime"),
                "box_office": m.get("BoxOffice"),
                "imdb_id": m.get("imdbID")
            })

        df = pd.DataFrame(rows)

        # Clean data types
        df["year"] = pd.to_numeric(df["year"], errors="coerce").astype("Int64")
        df["imdb_rating"] = pd.to_numeric(df["imdb_rating"], errors="coerce")
        df["imdb_votes"] = df["imdb_votes"].str.replace(",", "").pipe(pd.to_numeric, errors="coerce").astype("Int64")
        # Fix: str.extract returns a DataFrame, we need column 0 to get a Series
        df["runtime_min"] = df["runtime"].str.extract(r"(\d+)")[0].pipe(pd.to_numeric, errors="coerce").astype("Int64")

        return df

# Usage example
# collector = MovieDataCollector(OMDB_API_KEY)
# movies = collector.fetch_movies(["Inception", "The Matrix"])
# df = collector.to_dataframe(movies)
# print(df)

### Question 6.2: Add Search Functionality

Extend the `MovieDataCollector` class to add a `search_movies(query, max_results=50)` method that:
1. Searches for movies matching the query
2. Handles pagination to get up to `max_results` movies
3. For each search result, fetches the full movie details
4. Returns the detailed movie data

**Hint**: Search results only contain basic info (title, year, poster, imdbID). You need to use the imdbID to fetch full details.

In [ ]:
# YOUR CODE HERE
# Extend the MovieDataCollector class or add a method


### Question 6.3: Build a Genre-Based Dataset

Use your collector to build a dataset of popular movies from different genres:

1. Search for 10 movies each for: "action", "comedy", "drama", "horror", "sci-fi"
2. Combine all results into a single DataFrame
3. Remove any duplicates (some movies might appear in multiple searches)
4. Save to CSV

**Note**: This might take a while due to rate limiting. Start with fewer movies for testing.

In [ ]:
# YOUR CODE HERE


### Question 6.4: Data Quality Analysis

Using the dataset you created:

1. How many movies have missing IMDB ratings?
2. How many movies have missing box office data?
3. What's the distribution of ratings? (min, max, mean, median)
4. Which directors appear most frequently?
5. What's the average runtime by genre?

These quality checks will be important for Week 2 (Data Validation)!

In [ ]:
# YOUR CODE HERE


---

# Part 7: Challenge Problems

These are optional advanced exercises for those who finish early.

### Challenge 7.1: Rate Limit Handler

Create a `RateLimiter` class that:
1. Tracks how many requests have been made
2. Automatically adds delays to stay under a rate limit
3. Handles 429 (Too Many Requests) responses by waiting and retrying

```python
limiter = RateLimiter(requests_per_minute=30)
response = limiter.get("https://api.example.com/data")
```

In [ ]:
# YOUR CODE HERE


### Challenge 7.2: Async Movie Collector

The synchronous approach is slow because we wait for each request to complete.

Create an async version using `aiohttp` that can fetch multiple movies concurrently (while still respecting rate limits).

Compare the time to fetch 20 movies with sync vs async approach.

In [ ]:
# YOUR CODE HERE
# Hint: You'll need to install aiohttp: pip install aiohttp
# And use asyncio to run the async code


### Challenge 7.3: Multi-Source Data Fusion

Create a data collection pipeline that:
1. Fetches basic movie data from OMDb
2. Enriches it with additional data from another source (e.g., Wikipedia API for plot summaries)
3. Merges the data based on movie title/year
4. Handles cases where data is missing from one source

Wikipedia API example:
```
https://en.wikipedia.org/api/rest_v1/page/summary/Inception_(film)
```

In [ ]:
# YOUR CODE HERE


---

# Summary

In this lab, you learned:

1. **HTTP Fundamentals**: URLs, status codes, headers
2. **curl**: Command-line HTTP requests
3. **Python requests**: Programmatic data collection
4. **Error handling**: Timeouts, retries, status codes
5. **OMDb API**: Real-world movie data
6. **BeautifulSoup**: Web scraping when APIs don't exist
7. **Data pipelines**: Building reusable collection code

## Next Week

**Week 2: Data Validation & Quality**

The data we collected today is messy! Next week we'll learn:
- Schema validation with Pydantic
- Data type cleaning
- Handling missing values
- Quality metrics

---

## Submission

Save your completed notebook and submit:
1. This notebook with all cells executed
2. The CSV file of movies you collected
3. A brief summary (1 paragraph) of what you learned